# -*- coding: utf-8 -*-
"""Hospital_OPD_BottleneckAnalysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q11Tj-1Ih59oof4ZTkwKluUwaHD1n60V
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("HospitalOPD_BottleneckLabelled_10000.csv", encoding='latin1')
df.head()

df.info()
df.describe()

df.info()

df.head()

import pandas as pd
import matplotlib.pyplot as plt

# تحويل التواريخ
time_cols = [
    'event_date','appointment_date_and_time',
    'prescription_doctor_start_date_and_time','prescription_doctor_end_date_and_time',
    'lab_start_date_and_time','lab_completed_date_and_time','lab_report_generation_date_and_time',
    'image_start_date_and_time','image_end_date_and_time','image_report_generation_date_and_time',
    'timestamp'
]

for col in time_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

activity_bottleneck = (
    df.groupby('activity')['bottleneck_label']
    .mean()
    .sort_values(ascending=False) * 100
)

activity_bottleneck.head(10)

plt.figure(figsize=(12,5))
activity_bottleneck.head(10).plot(kind='bar', color='red')
plt.title('Top Activities Causing Bottlenecks (%)')
plt.ylabel('Percentage %')
plt.xticks(rotation=30)
plt.show()

waiting_by_activity = (
    df.groupby('activity')['waiting_time_minutes']
    .mean()
    .sort_values(ascending=False)
)

waiting_by_activity.head(10)

plt.figure(figsize=(12,5))
waiting_by_activity.head(10).plot(kind='bar', color='purple')
plt.title('Average Waiting Time per Activity (minutes)')
plt.ylabel('Minutes')
plt.xticks(rotation=30)
plt.show()

processing_by_activity = (
    df.groupby('activity')['processing_duration_minutes']
    .mean()
    .sort_values(ascending=False)
)

processing_by_activity.head(10)

plt.figure(figsize=(12,5))
processing_by_activity.head(10).plot(kind='bar', color='green')
plt.title('Average Processing Duration per Activity (minutes)')
plt.ylabel('Minutes')
plt.xticks(rotation=30)
plt.show()

processing_by_activity = (
    df.groupby('activity')['processing_duration_minutes']
    .mean()
    .sort_values(ascending=False)
)

processing_by_activity.head(10)

plt.figure(figsize=(12,5))
processing_by_activity.head(10).plot(kind='bar', color='green')
plt.title('Average Processing Duration per Activity (minutes)')
plt.ylabel('Minutes')
plt.xticks(rotation=30)
plt.show()

resource_load = (
    df.groupby('activity')['activity_resource_load']
    .mean()
    .sort_values(ascending=False)
)

resource_load.head(10)

plt.figure(figsize=(12,5))
resource_load.head(10).plot(kind='bar', color='steelblue')
plt.title('Activity Resource Load (Average)')
plt.ylabel('Load')
plt.xticks(rotation=30)
plt.show()

doctor_load = (
    df.groupby('doctor_name')['doctor_case_load']
    .mean()
    .sort_values(ascending=False)
)

doctor_load.head(10)

plt.figure(figsize=(12,5))
doctor_load.head(10).plot(kind='bar', color='brown')
plt.title('Doctor Case Load (Average)')
plt.ylabel('Cases')
plt.xticks(rotation=30)
plt.show()

summary = pd.DataFrame({
    'Avg Waiting': waiting_by_activity,
    'Avg Processing': processing_by_activity,
    'Avg Transition Delay': transition_delay,
    'Resource Load': resource_load,
    'Bottleneck %': activity_bottleneck
})

summary.head(10)